home:
    path: /
    controller: App\Controller\HomeController::index

# group_list:
#     path: /admin/groupes
#     controller: App\Controller\Admin\GroupController::group_list

# group_notes:
#     path: /admin/groupe/{groupId}/notes
#     controller: App\Controller\Admin\GroupController::group_notes

# group_notes_edit:
#     path: /admin/groupe/{groupId}/edit/{typeEval}
#     defaults:
#         typeEval: soutenance
#     controller: App\Controller\Admin\GroupController::edit_note



# evaluator_list:
#     path: /admin/evaluateurs
#     controller: App\Controller\Admin\EvaluatorController::list


list_note:
    path: /admin/liste_notes
    controller: App\Controller\Admin\GroupController::list_note

group_list:
    path: /admin/groupes
    controller: App\Controller\Admin\GroupController::group_list

group_notes:
    path: /admin/groupe/{groupId}/notes
    controller: App\Controller\Admin\GroupController::group_notes

list_notes_eval:
    path: /admin/groupe/{groupId}/edit/{typeEval}
    controller: App\Controller\Admin\GroupController::list_eval

evaluator_list:
    path: /admin/evaluateurs
    controller: App\Controller\Admin\EvaluatorController::list

account:
    path: /profil
    controller: App\Controller\UserController::index

# email:
#     path: /admin/email
#     controller: App\Controller\Admin\EmailController::index

maintenance:
    path: /maintenance
    controller: App\Controller\MaintenanceController::index

password_reset:
    path: /mot-de-passe/recuperation
    controller: App\Controller\Auth\AuthController::password_reset_form

define_dates:
    path: /admin/acces-au-site
    controller: App\Controller\Admin\AccessController::dates_index

add_define_dates:
    path: /admin/acces-au-site/ajouter
    controller: App\Controller\Admin\AccessController::add_dates_index

#index:
#    path: /
#    controller: App\Controller\DefaultController::index

edit_jury:
    path: /composition-des-jury
    controller: App\Controller\Admin\JuryController::show

show_groupAB:
    path: /composition-des-groupes
    controller: App\Controller\Admin\GroupABController::show

# Path view evaluator

eval_list_note:
    path: /liste_notes
    controller: App\Controller\Admin\GroupController::list_note

eval_group_list:
    path: /groupes
    controller: App\Controller\Evaluator\GroupController::group_list

eval_group_notes_sout:
    path: /groupe/{groupId}/soutenance
    controller: App\Controller\Evaluator\GroupController::group_notes_sout

eval_group_notes_poster:
    path: /groupe/{groupId}/poster
    controller: App\Controller\Evaluator\GroupController::group_notes_poster

eval_group_notes_indiv:
    path: /groupe/{groupId}/individuelle
    controller: App\Controller\Evaluator\GroupController::group_notes_indiv

eval_group_final:
    path: /groupe/{groupId}/final
    controller: App\Controller\Evaluator\GroupController::group_notes_final

# routes Notation

eval_showNoteGroupSout:
    path: /groupes/session-soutenance
    controller: App\Controller\Evaluator\GroupController::showNoteGroupSout

eval_showNoteGroupPost:
    path: /groupes/session-poster
    controller: App\Controller\Evaluator\GroupController::showNoteGroupPost

eval_showNoteGroupIndiv:
    path: /groupes/edition-notes-du-tuteur
    controller: App\Controller\Evaluator\GroupController::showNoteGroupIndiv