home:
    path: /
    controller: App\Controller\HomeController::index

# group_list:
#     path: /admin/groupes
#     controller: App\Controller\Admin\GroupController::group_list

# group_notes:
#     path: /admin/groupe/{groupId}/notes
#     controller: App\Controller\Admin\GroupController::group_notes

# group_notes_edit:
#     path: /admin/groupe/{groupId}/edit/{typeEval}
#     defaults:
#         typeEval: soutenance
#     controller: App\Controller\Admin\GroupController::edit_note



# evaluator_list:
#     path: /admin/evaluateurs
#     controller: App\Controller\Admin\EvaluatorController::list


group_list:
    path: /admin/groupes
    controller: App\Controller\Admin\GroupController::group_list

group_notes:
    path: /admin/groupe/{groupId}/notes
    controller: App\Controller\Admin\GroupController::group_notes

group_notes_edit:
    path: /admin/groupe/{groupId}/edit/{typeEval}
    defaults:
        typeEval: soutenance
    controller: App\Controller\Admin\GroupController::edit_note

# group_notes_edit_poster:
#     path: /groupe/{groupId}/edit/{typeEval}
#     defaults:
#         typeEval: poster
#     controller: App\Controller\Admin\GroupController::edit_note


evaluator_list:
    path: /admin/evaluateurs
    controller: App\Controller\Admin\EvaluatorController::list

account:
    path: /profil
    controller: App\Controller\UserController::index

email:
    path: /admin/email
    controller: App\Controller\Admin\EmailController::index

maintenance:
    path: /maintenance
    controller: App\Controller\MaintenanceController::index

password_reset:
    path: /mot-de-passe/recuperation
    controller: App\Controller\Auth\AuthController::password_reset_form

define_dates:
    path: /admin/acces-au-site
    controller: App\Controller\Admin\AccessController::dates_index

add_define_dates:
    path: /admin/acces-au-site/ajouter
    controller: App\Controller\Admin\AccessController::add_dates_index


planning:
    path: /planning
    controller: App\Controller\Admin\PlanningController::planning

#index:
#    path: /
#    controller: App\Controller\DefaultController::index

edit_jury:
    path: /composition-des-jury
    controller: App\Controller\Admin\JuryController::show

show_groupAB:
    path: /composition-des-groupes
    controller: App\Controller\Admin\GroupABController::show

# Path view evaluator
evaluator_home:
    path: /eval
    controller: App\Controller\Evaluator\EvaluatorController::index

eval_group_list:
    path: /groupes
    controller: App\Controller\Evaluator\GroupController::group_list

eval_group_notes_sout:
    path: /groupe/{groupId}/soutenance
    controller: App\Controller\Evaluator\GroupController::group_notes_sout

eval_group_notes_poster:
    path: /groupe/{groupId}/poster
    controller: App\Controller\Evaluator\GroupController::group_notes_poster

planning_eval:
    path: /eval/planning
    controller: App\Controller\Evaluator\EvalPlanningController::planning

maintenance_eval:
    path: /eval/maintenance
    controller: App\Controller\MaintenanceController::eval

list_eval:
    path: /eval/list
    controller: App\Controller\Evaluator\EvalListController::list